# Generated by Django 4.1.5 on 2023-03-29 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the language', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=1000)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.language')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_tries', models.IntegerField(default=0)),
                ('correct_tries', models.IntegerField(default=0)),
                ('difficulty', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Wordlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('visibility', models.CharField(choices=[('pr', 'Private'), ('pl', 'Public'), ('re', 'Under review')], default='pr', help_text='Visibily status', max_length=2)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wordlists', to=settings.AUTH_USER_MODEL)),
                ('translations', models.ManyToManyField(help_text='The translations in this word list.', to='quiz.translation')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='How the word is spelled', max_length=200)),
                ('language', models.ForeignKey(help_text='The language of this word', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.language')),
                ('usage', models.ManyToManyField(blank=True, to='quiz.sentence')),
            ],
        ),
        migrations.AddField(
            model_name='translation',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='translations', to='quiz.word'),
        ),
        migrations.AddField(
            model_name='translation',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='words', to='quiz.word'),
        ),
    ]
