# Generated by Django 4.1.3 on 2022-11-27 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lijst',
            new_name='List',
        ),
    ]
