# Generated by Django 4.1.5 on 2023-01-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='tries',
            field=models.IntegerField(default=0),
        ),
    ]
