# Generated by Django 4.1.5 on 2023-03-26 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='word_one',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='word_two',
        ),
        migrations.AddField(
            model_name='translation',
            name='correct_tries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='translation',
            name='translation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quiz.word'),
        ),
        migrations.AddField(
            model_name='translation',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='quiz.word'),
        ),
        migrations.AddField(
            model_name='translation',
            name='wrong_tries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wordlist',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='word_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wordlist',
            name='translations',
            field=models.ManyToManyField(to='quiz.translation'),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
