# Generated by Django 4.1.5 on 2023-03-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_translation_tries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='tries',
            new_name='correct_tries',
        ),
        migrations.AddField(
            model_name='translation',
            name='wrong_tries',
            field=models.IntegerField(default=0),
        ),
    ]
