# Generated by Django 4.1.5 on 2023-03-26 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_remove_translation_word_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='usage',
            field=models.ManyToManyField(to='quiz.sentence'),
        ),
        migrations.AddField(
            model_name='wordlist',
            name='visibility',
            field=models.CharField(choices=[('pr', 'Private'), ('pl', 'Public'), ('re', 'Under review')], default='pr', help_text='Visibily status', max_length=2),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='The name of the language', max_length=200),
        ),
        migrations.AlterField(
            model_name='translation',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='translations', to='quiz.word'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='words', to='quiz.word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.ForeignKey(help_text='The language of this word', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.language'),
        ),
        migrations.AlterField(
            model_name='word',
            name='name',
            field=models.CharField(help_text='How the word is spelled', max_length=200),
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wordlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='translations',
            field=models.ManyToManyField(help_text='The translations in this word list.', to='quiz.translation'),
        ),
        migrations.DeleteModel(
            name='ExampleUsage',
        ),
    ]
