# Generated by Django 4.1.5 on 2023-03-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_word_usage_wordlist_visibility_alter_language_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordlist',
            old_name='published_date',
            new_name='date_published',
        ),
    ]
