# Generated by Django 4.1.5 on 2023-03-25 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_rename_tries_translation_correct_tries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlist',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='word_lists', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordlist',
            name='translations',
            field=models.ManyToManyField(to='quiz.translation'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='word_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations_from', to='quiz.word'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='word_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations_to', to='quiz.word'),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
