# Generated by Django 4.1.5 on 2023-03-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_rename_published_date_wordlist_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='usage',
            field=models.ManyToManyField(null=True, to='quiz.sentence'),
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
