# Generated by Django 4.1.5 on 2023-03-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_word_usage_alter_wordlist_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='usage',
            field=models.ManyToManyField(blank=True, to='quiz.sentence'),
        ),
    ]
