# Generated by Django 4.2 on 2023-04-04 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordlist',
            name='translations',
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='quiz.translation')),
                ('wordlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='quiz.wordlist')),
            ],
        ),
    ]
