# Generated by Django 4.2 on 2023-04-04 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_wordlist_translations_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
