# Generated by Django 4.2 on 2023-04-04 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_material_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
