# Generated by Django 4.2 on 2023-04-04 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_material_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='added',
            new_name='date_added',
        ),
        migrations.AlterField(
            model_name='wordlist',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
