# Generated by Django 4.2 on 2023-04-13 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='quiz.source'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='quiz.source'),
            preserve_default=False,
        ),
    ]
