# Generated by Django 4.2 on 2023-04-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_remove_source_url_sentence_sources_source_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='location',
        ),
        migrations.AddField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
