# Generated by Django 4.2 on 2023-04-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_remove_source_location_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='sources',
            field=models.ManyToManyField(to='quiz.source'),
        ),
    ]
