# Generated by Django 4.2 on 2023-04-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_word_sources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='source',
            new_name='sources',
        ),
    ]
