# Generated by Django 4.2 on 2023-04-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_rename_source_translation_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='difficulty',
        ),
    ]
