# Generated by Django 4.2 on 2023-04-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_remove_translation_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordlist',
            name='visibility',
            field=models.CharField(choices=[('pr', 'Private'), ('pl', 'Public'), ('re', 'Under review')], default='pl', help_text='Visibily status', max_length=2),
        ),
    ]
